import type { Pool } from 'pg';
import { createDatabase, requireEnv } from './client.js';

const DUPLICATE_OBJECT = '42710';

export interface RolePasswords {
  ingest: string;
  api: string;
}

/**
 * Creates the weather_ingest / weather_api least-privilege roles and grants described in
 * roles.sql. Implemented directly against the pg client (rather than shelling out to psql) so it
 * needs no extra tooling in the container image and is exercised by the same test suite as
 * migrate.ts / seed.ts. Idempotent: safe to run against a database where the roles and grants
 * already exist.
 */
export async function applyRoles(pool: Pool, passwords: RolePasswords): Promise<void> {
  for (const role of ['weather_ingest', 'weather_api']) {
    try {
      await pool.query(`CREATE ROLE ${role} LOGIN`);
    } catch (error) {
      if ((error as { code?: string }).code !== DUPLICATE_OBJECT) {
        throw error;
      }
    }
  }

  // PostgreSQL does not accept a bind parameter in the PASSWORD clause of ALTER ROLE (it is a
  // string literal position in the DDL grammar, not a query parameter), so the password is
  // quoted as a literal here instead. Passwords are generated by this project's own tooling
  // (docker-compose env / CI secrets), never user input, but the quote is still escaped per
  // standard SQL string-literal rules for defense in depth.
  const quoteLiteral = (value: string): string => `'${value.replace(/'/g, "''")}'`;
  await pool.query(`ALTER ROLE weather_ingest LOGIN PASSWORD ${quoteLiteral(passwords.ingest)}`);
  await pool.query(`ALTER ROLE weather_api LOGIN PASSWORD ${quoteLiteral(passwords.api)}`);

  const currentDatabaseResult = await pool.query<{ current_database: string }>(
    'SELECT current_database()',
  );
  const databaseRow = currentDatabaseResult.rows[0];
  if (!databaseRow) {
    throw new Error('Could not resolve current_database()');
  }
  const databaseName = databaseRow.current_database;

  await pool.query(`
    GRANT CONNECT ON DATABASE "${databaseName}" TO weather_ingest, weather_api;
    GRANT USAGE ON SCHEMA public TO weather_ingest, weather_api;

    -- weather_api: SELECT only, on every table that exists now and every table created hereafter.
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO weather_api;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO weather_api;

    -- weather_ingest: read everything (needs cities/providers/lookups to build upserts), but may
    -- only write to the tables the ingestion job actually populates.
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO weather_ingest;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO weather_ingest;

    GRANT INSERT, UPDATE ON ingest_runs, observations, forecast_hourly, forecast_daily
      TO weather_ingest;
    GRANT USAGE, SELECT ON SEQUENCE ingest_runs_id_seq TO weather_ingest;
    GRANT USAGE, SELECT ON SEQUENCE observations_id_seq TO weather_ingest;
    GRANT USAGE, SELECT ON SEQUENCE forecast_hourly_id_seq TO weather_ingest;
    GRANT USAGE, SELECT ON SEQUENCE forecast_daily_id_seq TO weather_ingest;
  `);

  // Neither role gets DELETE, DDL, or ownership on anything — only the owner connection (used by
  // migrate.ts / seed.ts) can alter schema or delete rows.
}

async function main(): Promise<void> {
  const { pool } = createDatabase(requireEnv('DATABASE_URL_OWNER'));
  try {
    await applyRoles(pool, {
      ingest: requireEnv('WEATHER_INGEST_PASSWORD'),
      api: requireEnv('WEATHER_API_PASSWORD'),
    });
    console.log('Roles applied.');
  } finally {
    await pool.end();
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((error: unknown) => {
    console.error('Applying roles failed:', error);
    process.exitCode = 1;
  });
}
